site_name: Fries Docs

nav:
  - 主页: index.md
  - 深大指北:
    - guidebook/forFreshman.md
    - 交通: guidebook/transportation.md
    - 地点 & 建筑: 
      - 粤海校区: guidebook/locations/yuehai.md
      - 西丽校区: guidebook/locations/xili.md
    - 设施 & 服务: guidebook/service.md
    
  - 大学时光:
    - 专业课程:
      - 机电与控制工程学院: szulife/courses/College_of_Mechatronics_and_Control_Engineering/index.md
     # - 物理与光电工程学院: SZU_life/page1.md
    - 水课: szulife/courses_in_water/waterCrouses.md
    #- 考试: 
    - 社团: szulife/clubs_in_szu/clubs_in_szu.md
    - 竞赛: szulife/competition/competitions.md
    - 项目: szulife/project/index.md
  - 参考手册: 
    - 校内黄页: reference/yellow_pages.md
    
  - 关于: about/about.md

theme:
  
  name: material #choose conf from 1 or 2
  
  ### conf1  when install with pip/docker
  #  name: material
  ###
  
  ### conf2  when install with git 
  #  name: null
  #  custom_dir: ../mkdocs-material/material
  #
  ## 404 page
  #  static_templates:
  #    - 404.html
  ###
  
  ## Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  #  logo: logo
  
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode 
    
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/team0ne1/fries-docs
repo_name: team0ne1/fries-docs
edit_uri: ""
copyright: Copyright &copy; 2021 - 2023 Team0ne

extra:

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/repository/docker/team0ne1/fries-docs
      name: Docker Hub
    - icon: material/email-open
      link: mailto:SZU-lib233@protonmail.com
      name: Email
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/gHAcZzVxpMs0ZGYx
      name: Telegram group

plugins:
    - search:
        lang:
        - en
        #- zh
