site_name: SZU Fries Docs

nav:
  - 主页: index.md
  - 深大指北:
    #- guidebook/forFreshman.md
    - 学院介绍: 
      - guidebook/szu_intro.md
      - 机电与控制工程学院: guidebook/colleges_intro/CMCE.md
    - 交通: guidebook/transportation.md
    - 地点 & 建筑:
      - guidebook/locations/index.md    
      - 粤海校区: guidebook/locations/yuehai.md
      - 西丽校区: guidebook/locations/xili.md
    - 校园网: guidebook/service/szu_network.md
    - 软件资源: guidebook/service/szu_software.md
    - 电力供应: guidebook/service/energy_supply_service.md
    - 快递收发: guidebook/service/package_express.md
    - 体育场馆: guidebook/service/sports_venues.md
    - 心理咨询: guidebook/szu_camhc.md
    - 奖学金申请: guidebook/applications4scholarships.md

  - 学术混子:
    - 自述: szulife/courses/index.md
    - 公共: 
      - 课程目录: szulife/courses/major/Public/index.md
      - 大学计算机: szulife/courses/major/Public/contents/大学计算机.md
      - 大学物理A: szulife/courses/major/Public/contents/大学物理A.md
      - 大物实验: szulife/courses/major/Public/contents/大学物理实验.md
      - 马克思主义基本原理: szulife/courses/major/Public/contents/马克思主义基本原理.md

    - 机电与控制工程学院: 
      - 课程目录: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/index1.md
      - 早期工程实践: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/早期工程实践.md
      - 模拟电子技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/模拟电子技术.md
      - 数字电子技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/数字电子技术.md
      - 线性代数: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/线性代数.md
      - 单片机原理与接口技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/单片机原理与接口技术.md
      - 信号与系统: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/信号与系统.md
      - 模式识别: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/模式识别.md
      - 电力电子技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/电力电子技术.md
      - 自动控制原理: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/自动控制原理.md
      - DSP原理与应用: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/DSP原理与应用.md
      - 计算机控制技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/计算机控制技术.md 
      - 传感器与检测技术: szulife/courses/major/College_of_Mechatronics_and_Control_Engineering/传感器与检测技术.md
    - UOOC: szulife/courses_in_water/uooc.md
    - 公选课: szulife/courses_in_water/public.md
    - 转专业: szulife/change_major/change_major.md
    
  # - 社团: szulife/clubs_in_szu/clubs_in_szu.md
  - 参考手册: 
    - 校历: reference/school_calendar.md
    - 校内黄页: reference/yellow_pages.md
    - 深大考古: reference/szu_history.md
    - 媒体: reference/media.md
    
  - 关于: about/about.md

theme:
  
  name: material #choose conf from 1 or 2
  
  ### conf1  when install with pip/docker
  #  name: material
  ###
  
  ### conf2  when install with git 
  #  name: null
  #  custom_dir: ../mkdocs-material/material
  #
  ## 404 page
  #  static_templates:
  #    - 404.html
  ###
  
  ## Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/logo.png
  logo: images/logo.png
  icon:
    repo: fontawesome/brands/github
  #  logo: logo
  
  palette:
    - scheme: fries-docs
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode 
    
  features:
    - navigation.instant
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    #- navigation.indexes
    - navigation.expand
    
    
    #- toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - meta
  - pymdownx.keys
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


repo_url: https://github.com/team0ne1/szu-fries-docs
repo_name: team0ne1/szu-fries-docs
edit_uri: edit/pub/docs/
copyright: Copyright &copy; 2021 - 2023 SZU Fries Docs

extra:

  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/team0ne1/szu-fries-docs_pub
      name: Docker Hub
    - icon: material/email-open
      link: mailto:szulib.docs@outlook.com
      name: Email
    - icon: fontawesome/brands/telegram
      link: https://t.me/joinchat/gHAcZzVxpMs0ZGYx
      name: Telegram group
      




plugins:
    - search:
        lang:
        - en
        separator: '[\s\u200b\-]'
        #- zh
    - markdownextradata
    - git-revision-date-localized:
        #enable_creation_date: true
        fallback_to_build_date: true
        type: timeago
    

        