name: Build and publish szu-fire-docs_pub image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the pub branch
  push:
    branches: [ pub ]
    paths-ignore:
      - 'README**.md'
      - 'LICENSE'

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository }}_pub:${{ github.sha }}
            ${{ github.repository }}_pub:latest
  
